### ISSUE TITLE
Chrome store publish rejected

### ISSUE THREAD

**Issue by laubonghaudoi** [CanCLID/inject-jyutping#10]
我喺開發者頁面收到呢個提示
<img width="1821" alt="image" src="https://github.com/user-attachments/assets/eb249e41-5c77-49ee-a67b-e9db3bdb190e">

https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3

**Comment by graphemecluster** [comment]
咁奇怪？而家已經係 V3 嚟㗎喇噃

**Comment by laubonghaudoi** [comment]
可能係講緊舊版，等新嘅發佈應該會好返

**Comment by laubonghaudoi** [comment]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/381b1e57-5eb5-4115-8f0d-d63adce044a0">
@graphemecluster 啱啱得到呢個更新，話係

Violation type:	[Spam and Placement in the Store](https://developer.chrome.com/webstore/program_policies#spam)
Details

- Violation reference ID: [Yellow Magnesium](https://developer.chrome.com/docs/webstore/troubleshooting/#does-not-work)
- Violation: Not providing promised functionality
"Invalid package error is present for a node module file request is content script but not present in code package"
- How to rectify: Test the code that you submit to the web store locally, verify that your submission contains the files you expect at the paths you expect, and is working as intended. For more information, please refer to the [documentation](https://developer.chrome.com/docs/extensions/mv3/intro/) and migration [checklist](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/) on Manifest V3 version.
- Relevant section of the program policy: Extensions with broken functionality - such as dead sites or non-functioning features - are not allowed.

**Comment by graphemecluster** [comment]
我估係因為 detect 到有 directory name 叫 `node_modules` 就自動黃標，cp 出嚟就冇問題？（亂估）

**Comment by graphemecluster** [comment]
其他 store 有冇問題？

**Comment by laubonghaudoi** [comment]
我冇其他store，firefox嘅發佈係 @ayaka14732 整嘅，要問佢

**Comment by graphemecluster** [comment]
@laubonghaudoi 你而家試多次？

**Comment by laubonghaudoi** [comment]
已經提交，等結果

**Comment by laubonghaudoi** [comment]
好似又拒絕咗，但係佢上面寫住嘅版本號仲係0.4.0唔係0.4.1，你係咪唔記得更新個版本號？
<img width="1917" alt="image" src="https://github.com/user-attachments/assets/753868c1-ee43-4d91-9632-05bdb4c97c03">

**Comment by laubonghaudoi** [comment]
呢度仲係 0.4.0 唔係 0.4.1 https://github.com/CanCLID/inject-jyutping/blob/main/manifest.json#L4

**Comment by graphemecluster** [comment]
Reproduce 唔到，我呢度係 work 嘅
Version number 的確係我唔記得更新（改咗 package.json 唔記得改 manifest.json），不過其實冇所謂，因為 0.4.0 根本未發佈

**Comment by laubonghaudoi** [comment]
咁奇怪，噉而家點算？我有冇辦法可以幫你debug？

**Comment by graphemecluster** [comment]
唔會，package.json 係 for development 嘅，zip 度冇

**Comment by graphemecluster** [comment]
@laubonghaudoi @ayaka14732 試下呢個新 release
https://github.com/CanCLID/inject-jyutping/releases/tag/0.5.0
放上 Chrome、Firefox、Edge
※ 有 minify 到，記得交 source code

**Comment by laubonghaudoi** [comment]
啱啱提交咗，等結果。佢個提交係冇得交源代碼嘅，淨得個 zip 交上去。

**Comment by laubonghaudoi** [comment]
終於成功 https://chromewebstore.google.com/detail/inject-jyutping/lfgpgjkjglogbndlkikjgbbfoiofbdjp @laubonghaudoi @graphemecluster 唔該晒！
