### ISSUE TITLE
「匿」嘅音可能註錯咗喇

### ISSUE THREAD

**Issue by tsunhua** [CanCLID/inject-jyutping#6]
本人初學者，我發現個問題，「匿」喺[嗰度](https://www.cantonese.com.hk/animalfarm/text/ch1/) 註咗 lik1，但喺 [粵音資料集叢](https://jyut.net/query?q=%E5%8C%BF) 度係 nik1 / nei1，請睇下邊張圖：

![image](https://github.com/CanCLID/inject-jyutping/assets/11910355/6a114185-8104-478e-996e-08f30a928a3d)

**Comment by laubonghaudoi** [comment]
@tsunhua https://github.com/CanCLID/rime-cantonese-upstream/blob/main/char.csv#L8306

**Comment by graphemecluster** [comment]
@laubonghaudoi 你畀佢睇都冇用，inject-jyutping 而家係冇用到上游詞表資料嘅，短期內會有大規模更新

**Comment by laubonghaudoi** [comment]
總之呢個唔關個上游詞庫事，係 inject-jyutping 本身嘅問題
